version: "3.9"

services:
  pgsqldb:
    container_name: pgsqldb
    image: postgres
    environment:
      POSTGRES_USER: rajiv
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-app-1
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsqldb:5432/todo-app-1
      SPRING_DATASOURCE_USERNAME: rajiv
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - pgsqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: